apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-microservice
spec:
  selector:
    matchLabels:
      app: library-microservice
  template:
    metadata:
      labels:
        app: library-microservice
    spec:
      containers:
        - name: book-catalog
          image: sit722seremregistry.azurecr.io/inventory-management:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: postgresql://sit722_15g3_user:VS9q7i2ulpfI3mx3l2Er7bpQi2i9pWuV@dpg-crm4tk88fa8c73a1vnp0-a.oregon-postgres.render.com/sit722_15g3
        - name: inventory-management
          image: sit722seremregistry.azurecr.io/book-catalog:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgresql://sit722_15g3_user:VS9q7i2ulpfI3mx3l2Er7bpQi2i9pWuV@dpg-crm4tk88fa8c73a1vnp0-a.oregon-postgres.render.com/sit722_15g3
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: library-microservice
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: library-microservice
  ports:
    - port: 8002
      targetPort: 8002
  type: LoadBalancer
